language: php
php:
  - '7.2'
  - hhvm # on Trusty only
  - nightly

install:
  - php vendor/vendors.php

script:

    - echo "Executing Tests"
    - cd $HOME/gopath/src/github.com/$USER_NAME/$REPO_NAME
    - make $TEST_TARGET
